<?php
/**
 * $Id: help_cs_drivers.php 632 2008-04-10 19:40:56Z rdg $
 * 
 * LICENSE INFORMATION
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details:
 * 
 * http://www.gnu.org/copyleft/gpl.html
 * 
 * 
 * @author Renato De Giovanni <renato [at] cria . org . br>
 */

$a = 'left'; // text alignment

$name = 'Conceptual schema drivers';

$doc = <<<EOT
TapirLink can load concepts from different types of conceptual schemas.

<u><b>Old DarwinCore (tied to DiGIR):</b></u>

XML Schema format where each concept is defined as a global element with a "substitutionGroup" attribute referencing one of the following elements that are defined under the DiGIR namespace: searchableData, returnableData or searchableReturnableData. Example: <a href="http://digir.net/schema/conceptual/darwin/2003/1.0/darwin2.xsd" target="_new">darwin2.xsd</a>. Concept identifiers are generated by concatenating the schema namespace with a forward slash and then the element name.

<u><b>New DarwinCore:</b></u>

XML Schema format where each concept is defined as a global element with a "substitutionGroup" attribute referencing the "dwElement" from the namespace http://rs.tdwg.org/dwc/dwelement. Example: <a href="http://rs.tdwg.org/dwc/tdwg_dw_core.xsd" target="_new">tdwg_dw_core.xsd</a>. Concept identifiers are generated by concatenating the schema namespace with the element name.

<u><b>CNS text file:</b></u>

Text format where each conceptual schema is defined under a [concept_source] section. Concepts are defined after the [aliases] section as key-value pairs (alias = id). Example: <a href="http://rs.tdwg.org/tapir/cns/alias.txt" target="_new">alias.txt</a>. If the file contains more than one conceptual schema, only concepts from the last schema will be loaded. To specify another schema, append "#schema_alias" to the URL.

<u><b>CNS XML file:</b></u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>&lt;&lt;------------ Preferred format!</i>

XML format where each conceptual schema is defined inside a &lt;schema&gt; element. Example: <a href="http://rs.tdwg.org/tapir/cns/dublin_core_1_1.xml" target="_new">dublin_core_1_1.xml</a>. This is the preferred format because it contains all necessary information in a single, well-defined and XML-parseable file. If the file contains more than one conceptual schema, only concepts from the first schema will be loaded. To specify another schema, append "#schema_alias" to the URL.

EOT;

include( '../templates/help.tmpl.php' );

?>