
          <!-- beginning of DataSourceForm -->
          <br/>
          <table align="center" width="92%" cellspacing="1" cellpadding="1" bgcolor="#999999">
           <tr bgcolor="#ffffee"><td align="left" valign="middle" width="25%"><span class="label"><?php print(TP_MANDATORY_FIELD_FLAG); ?>Driver: </span></td><td align="left" valign="middle" width="75%"><?php print(TpHtmlUtils::GetCombo('dbtype',$r_data_source->GetDriverName(),$this->GetOptions('adodbDrivers'), false, false, "document.forms[1].refresh.value='showTemplate';document.forms[1].submit()")); ?><br/><span class="tip">see: </span><a href="http://phplens.com/lens/adodb/docs-adodb.htm#drivers" class="tip" target="_new">http://phplens.com/lens/adodb/docs-adodb.htm#drivers</a></td></tr>
           <tr bgcolor="#ffffee"><td align="left" valign="middle" width="25%"><span class="label"><?php print(TP_MANDATORY_FIELD_FLAG); ?>Database encoding: </span></td><td align="left" valign="middle" width="75%"><?php print(TpHtmlUtils::GetCombo('encoding',$r_data_source->GetEncoding(),$this->GetOptions('encodings'))); ?><br/><span class="tip">see: </span><a href="http://www.php.net/manual/en/ref.mbstring.php" class="tip" target="_new">http://www.php.net/manual/en/ref.mbstring.php</a><br/><span class="tip">note: If you are unsure about this setting, you can run an encoding test from the resource front page (after finishing the resource configuration).</span></td></tr>
           <tr bgcolor="#ffffee"><td align="left" valign="middle" width="25%"><span class="label"><?php print(TP_MANDATORY_FIELD_FLAG); ?>DSN or Hostname: </span></td><td align="left" valign="middle" width="75%"><input type="text" name="constr" value="<?php print(htmlspecialchars($r_data_source->GetConnectionString())); ?>" size="70"><?php if ($this->mTemplate): ?><br/><span class="tip">there is a template available <a href="help.php?name=<?php print($this->mTemplateTitle); ?>&amp;doc=<?php print($this->mTemplate); ?>" <?php printf("onClick=\"window.open('help.php?name=%s&amp;doc=%s','help','width=600,height=140,menubar=no,toolbar=no,scrollbars=yes,resizable=yes,personalbar=no,locationbar=no,statusbar=no').focus(); return false;\" style=\"text-decoration:none;\"", $this->mTemplateTitle, $this->mTemplate); ?>">here</a></span><?php endif; ?></td></tr>
           <tr bgcolor="#ffffee"><td align="left" valign="middle" width="25%"><span class="label"><?php print(TP_MANDATORY_FIELD_FLAG); ?>Username: </span></td><td align="left" valign="middle" width="75%"><input type="text" name="uid" value="<?php print($r_data_source->GetUsername()); ?>" size="20"></td></tr>
           <tr bgcolor="#ffffee"><td align="left" valign="middle" width="25%"><span class="label">Password: </span></td><td align="left" valign="middle" width="75%"><input type="password" name="pwd" value="<?php print($r_data_source->GetPassword()); ?>" size="20"></td></tr>
           <tr bgcolor="#ffffee"><td align="left" valign="middle" width="25%"><span class="label"><?php print(TP_MANDATORY_FIELD_FLAG); ?>Database name: </span></td><td align="left" valign="middle" width="75%"><input type="text" name="database" value="<?php print($r_data_source->GetDatabase()); ?>" size="20"></td></tr>
          </table>
          <p class="label_required"><?php print(TP_MANDATORY_FIELD_FLAG); ?>Indicates mandatory fields.<br/>
			  To set up the connexion parameters using a DSN string, fill in "DSN or Hostname" with the DSN string.<br/>
			  Otherwise, fill in "DSN or Hostname" with the host name or adress, and fill in the next 3 fields (username, password, db name).
		  </p>
          <br/>
          <!-- end of DataSourceForm -->
